### ISSUE TITLE
Errors when running tests

### ISSUE THREAD

**Issue by tonespi** [cofin/litestar-fullstack#17]
On a fresh clone of the repo some of the integration tests in test_accounts.py and test_teams.py raise

```
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

Been poking at it for a while and can't quite figure out what is going on

**Comment by cofin** [comment]
@tonespi thanks for reporting this.  I'm still fleshing out the tests a bit, so I'm not surprised on this.  I'll try to reproduce and fix this over the weekend.

**Comment by cofin** [comment]
@tonespi take a look at the updated team tests and let me know if that works for you.

**Comment by cofin** [comment]
I believe this should be resolved in the latest push.  Feel free to reply here if you continue to have issues.

**Comment by tonespi** [comment]
Unfortunately the tests still fail.

I have two small commits fixing some build issues and a fix for patching redis in the integration tests.

They unfortunately don't fix this issue but they do allow a clean build from scratch.
